### ISSUE TITLE
Update 14.10

### ISSUE THREAD

**Issue by ghostss2016** [Wend4r/mms-server_steam_account#5]
today, after the update, it gives an error 500.

**Comment by Wend4r** [comment]
MM:S plugin works for me
![image](https://github.com/Wend4r/mms-server_steam_account/assets/47463683/a9f7ec66-ead7-41eb-98bc-7646d7e56c51)
(also on the Windows platform)

Please, check a token validity on https://steamcommunity.com/dev/managegameservers
If the problem is still actual, send your console log
